[versions]
# Library and plugin versions
kotlin = "2.3.21"
kotlinx = "1.10.2"
composeMultiplatform = "1.10.3"
mavenPublish = "0.36.0"

# library module's configuration and publishing information
library-group = "io.github.sudarshanmhasrup.splashify"
library-artifactId = "splashify"
library-version = "1.0.0-alpha1"

# sample module's configuration information
sample-group = "com.sample.app"
sample-version = "1.0.0"
sample-mainClass = "com.sample.app.MainAppKt"

# sample module's distribution information
sample-distributionPackageName = "com.sample.app"
sample-distributionPackageVersion = "1.0.0"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx" }
compose-multiplatform-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-multiplatform-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }

[bundles]
compose-multiplatform = ["compose-multiplatform-ui", "compose-multiplatform-foundation"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }